--
-- Create dbs and users and privs
--
CREATE USER 'developer'@'localhost' IDENTIFIED BY PASSWORD '*AD45273B9D78E0BCD2BF12ED7D4DBC0C924D54D6';
GRANT CREATE TEMPORARY TABLES,DELETE,INSERT,LOCK TABLES,SELECT,SHOW VIEW,UPDATE ON *.* TO 'developer'@'localhost';
--
CREATE USER 'partnerpath'@'localhost' IDENTIFIED BY PASSWORD '*46C787A7D3A02A462CECAF28837A7E38871FA4A0';
GRANT SELECT,INSERT,DELETE,UPDATE ON *.* TO 'partnerpath'@'localhost';
--
CREATE USER 'dba'@'localhost' IDENTIFIED BY PASSWORD '*4EFBC0B3D186109B7D7623263EDA899A2F78CBBF';
GRANT ALL ON *.* TO 'dba'@'localhost' WITH GRANT OPTION;
--
CREATE USER 'migration'@'localhost' IDENTIFIED BY PASSWORD '*17EEB63E09736FDABDB8BDC1989005E86A39EF88';
GRANT ALTER,ALTER ROUTINE,CREATE,CREATE ROUTINE,CREATE TEMPORARY TABLES,CREATE VIEW,DELETE,DROP,EXECUTE,INDEX,INSERT,LOCK TABLES,SELECT,UPDATE ON *.* TO 'migration'@'localhost';
--
CREATE DATABASE PP DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE DEMO DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

